@startuml
actor "ESP32/DHT22" as ESP

boundary "simulateur.html\nWokwi IoT" as Sim

control "FastAPI WebSocket\n/ws/capteurs" as WS

database "Table capteurs" as Capteurs
database "Table donnees_capteurs" as Data
database "Table pannes" as Pannes

boundary "AdminDashboard.js" as Dash

ESP -> Sim : envoyer température/humidité

Sim -> WS : WebSocket JSON data

WS -> Capteurs : vérifier capteur_id

WS -> Data : INSERT température,\nhumidité, date

alt température > 40
WS -> Pannes : INSERT panne surchauffe
end

alt humidité > 85
WS -> Pannes : INSERT panne humidité
end

WS --> Dash : données temps réel WebSocket

@enduml
